"use client";

import { useState } from "react";
import { NotebookLayout } from "../notebook-layout";
import { useParams } from "next/navigation";
import { Repeat, Check } from "lucide-react";
import { useLearnLM } from "@/lib/learnlm-data";

export default function NotebookReviewPage() {
  const params = useParams(); const notebookId = params.id as string;
  const { getNotebook, getFlashcards, reviewFlashcard } = useLearnLM();
  const notebook = getNotebook(notebookId); const reviewItems = getFlashcards(undefined, notebookId).filter((f) => f.nextReview <= Date.now()).concat(getFlashcards(undefined, notebookId).filter((f) => f.nextReview > Date.now()).slice(0, 4));
  const [currentItem, setCurrentItem] = useState(0); const [showAnswer, setShowAnswer] = useState(false); const [completed, setCompleted] = useState<string[]>([]);
  const item = reviewItems[currentItem];
  const handleResponse = (quality: number) => { if (!item) return; reviewFlashcard(item.id, quality); setCompleted((prev) => [...prev, item.id]); if (currentItem < reviewItems.length - 1) { setCurrentItem((p) => p + 1); setShowAnswer(false); } };
  if (!notebook) return null;
  return <NotebookLayout notebookId={notebookId} notebookTitle={notebook.title} notebookColor={notebook.color}><div className="flex items-center gap-3 mb-6"><div className="w-10 h-10 bg-violet-100 rounded-lg flex items-center justify-center"><Repeat className="w-5 h-5 text-violet-600" /></div><div><h2 className="text-xl font-bold text-slate-900">Spaced Repetition Review</h2><p className="text-sm text-slate-500">{reviewItems.length} items in this notebook queue</p></div></div>{!item ? <div className="bg-white rounded-xl border border-slate-200 p-8 text-center text-slate-600">No review items yet.</div> : <><div className="flex gap-2 mb-6 overflow-x-auto pb-2">{reviewItems.map((ri, idx) => <button key={ri.id} onClick={() => { setCurrentItem(idx); setShowAnswer(false); }} className={`shrink-0 w-10 h-10 rounded-lg flex items-center justify-center text-sm font-medium transition-all ${idx === currentItem ? "bg-indigo-600 text-white ring-2 ring-indigo-300" : completed.includes(ri.id) ? "bg-emerald-100 text-emerald-700" : ri.nextReview < Date.now() ? "bg-red-100 text-red-700" : "bg-slate-100 text-slate-600"}`}>{completed.includes(ri.id) ? <Check className="w-4 h-4" /> : idx + 1}</button>)}</div><div className="bg-white rounded-xl border border-slate-200 p-6"><div className="flex items-center gap-2 mb-4"><span className="text-xs font-medium px-2.5 py-1 rounded-full bg-amber-100 text-amber-700">Flashcard</span><span className="text-xs font-medium px-2.5 py-1 rounded-full bg-slate-100 text-slate-600">{item.nextReview <= Date.now() ? "Today" : "Upcoming"}</span><span className="text-xs text-slate-400 ml-auto">Interval: {item.interval} days</span></div><p className="text-xl font-semibold text-slate-900 mb-6">{item.front}</p>{!showAnswer ? <button onClick={() => setShowAnswer(true)} className="w-full bg-indigo-600 text-white py-3 rounded-lg font-medium hover:bg-indigo-700 transition-colors">Show Answer</button> : <><div className="bg-slate-50 rounded-lg p-4 mb-4"><p className="text-sm text-slate-700">{item.back}</p></div><div className="grid grid-cols-4 gap-2">{["Again", "Hard", "Good", "Easy"].map((label, i) => <button key={label} onClick={() => handleResponse(i === 0 ? 1 : i === 1 ? 2 : i === 2 ? 4 : 5)} className={`py-2.5 rounded-lg font-medium text-sm transition-colors ${i === 0 ? "bg-red-100 text-red-700 hover:bg-red-200" : i === 1 ? "bg-amber-100 text-amber-700 hover:bg-amber-200" : i === 2 ? "bg-emerald-100 text-emerald-700 hover:bg-emerald-200" : "bg-blue-100 text-blue-700 hover:bg-blue-200"}`}>{label}</button>)}</div></>}</div></>}</NotebookLayout>;
}
