"use client";

import { useState } from "react";
import Link from "next/link";
import { Repeat, Target } from "lucide-react";
import { useLearnLM } from "@/lib/learnlm-data";

export default function ReviewPage() {
  const { state, getFlashcards, reviewFlashcard } = useLearnLM();
  const items = getFlashcards().map((f) => {
    const unit = state.units.find((u) => u._id === f.unitId)!; const nb = state.notebooks.find((n) => n._id === unit.notebookId)!;
    return { ...f, notebookId: nb._id, notebookTitle: nb.title, unitTitle: unit.title, due: f.nextReview <= Date.now() ? "Today" : "Tomorrow", type: "flashcard" as const };
  });
  const dueToday = items.filter((r) => r.nextReview <= Date.now());
  const queue = dueToday.length ? dueToday : items.slice(0, 8);
  const [currentItem, setCurrentItem] = useState(0); const [showAnswer, setShowAnswer] = useState(false); const [completed, setCompleted] = useState<string[]>([]);
  const item = queue[currentItem];
  const handleResponse = (quality: number) => { if (!item) return; reviewFlashcard(item.id, quality); setCompleted((prev) => [...prev, item.id]); const nextIdx = queue.findIndex((r, idx) => idx > currentItem && !completed.includes(r.id)); if (nextIdx >= 0) { setCurrentItem(nextIdx); setShowAnswer(false); } };
  return <div className="min-h-screen bg-slate-50"><div className="bg-white border-b border-slate-200 px-8 py-6"><div className="flex items-center gap-3"><div className="w-10 h-10 bg-violet-100 rounded-lg flex items-center justify-center"><Repeat className="w-5 h-5 text-violet-600" /></div><div><h1 className="text-2xl font-bold text-slate-900">Spaced Repetition Review</h1><p className="text-sm text-slate-500">{queue.length} items due across all notebooks</p></div></div></div><div className="max-w-2xl mx-auto p-6">{!item ? <div className="bg-white rounded-xl border border-slate-200 p-8 text-center text-slate-600">Nothing due. Add or generate study materials to build your review queue.</div> : <><div className="flex gap-2 mb-6 overflow-x-auto pb-2">{queue.map((ri, idx) => <button key={ri.id} onClick={() => { setCurrentItem(idx); setShowAnswer(false); }} className={`shrink-0 px-3 py-2 rounded-lg flex items-center gap-2 text-sm font-medium transition-all ${idx === currentItem ? "bg-violet-600 text-white" : completed.includes(ri.id) ? "bg-emerald-100 text-emerald-700" : ri.due === "Today" ? "bg-slate-100 text-slate-600" : "bg-blue-100 text-blue-700"}`}><span className="text-xs">🃏</span>{ri.notebookTitle}</button>)}</div><div className="bg-white rounded-xl border border-slate-200 p-6 mb-6"><div className="flex items-center gap-2 mb-4"><span className="text-xs font-medium px-2.5 py-1 rounded-full bg-violet-100 text-violet-700">Flashcard</span><span className="text-xs font-medium px-2.5 py-1 rounded-full bg-slate-100 text-slate-600">{item.due}</span><span className="text-xs text-slate-400 ml-auto">Interval: {item.interval}d</span></div><p className="text-xl font-semibold text-slate-900 mb-6">{item.front}</p>{!showAnswer ? <button onClick={() => setShowAnswer(true)} className="w-full bg-violet-600 text-white py-3 rounded-lg font-medium hover:bg-violet-700 transition-colors">Show Answer</button> : <><div className="bg-slate-50 rounded-lg p-4 mb-4"><p className="text-sm text-slate-700">{item.back}</p></div><div className="grid grid-cols-4 gap-2">{[["Again",1,"bg-red-100 text-red-700"],["Hard",2,"bg-amber-100 text-amber-700"],["Good",4,"bg-emerald-100 text-emerald-700"],["Easy",5,"bg-blue-100 text-blue-700"]].map(([label, q, cls]) => <button key={label as string} onClick={() => handleResponse(q as number)} className={`py-2.5 rounded-lg font-medium text-sm transition-colors ${cls} hover:opacity-80`}>{label}</button>)}</div></>}</div><Link href={`/notebook/${item.notebookId}/units/${item.unitId}`} className="w-full bg-violet-600 text-white py-3 rounded-lg font-medium hover:bg-violet-700 transition-colors flex items-center justify-center gap-2"><Target className="w-4 h-4" /> Review {item.unitTitle}</Link></>}</div></div>;
}
